// ----------------------------------------------------------------------
// File generated by NStack Translations Generator v5.0.
//
// Copyright (c) 2019 Nodes ApS
//
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of this software and associated documentation files (the
// "Software"), to deal in the Software without restriction, including
// without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to
// permit persons to whom the Software is furnished to do so, subject to
// the following conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// ----------------------------------------------------------------------

import Foundation
import NStackSDK

#if canImport(NLocalizationManager)
import NLocalizationManager
#endif

#if canImport(LocalizationManager)
import LocalizationManager
#endif

public var lo: Localizations {
    guard let manager = NStack.sharedInstance.localizationManager else {
        return Localizations()
    }
    return try! manager.localization()
}

public var tr: Localizations { lo }

public final class Localizations: LocalizableModel {
    public var defaultSection = DefaultSection()
    public var error = Error()

    enum CodingKeys: String, CodingKey {
        case defaultSection = "default"
        case error
    }

    public override init() { super.init() }

    public required init(from decoder: Decoder) throws {
        super.init()
        let container = try decoder.container(keyedBy: CodingKeys.self)
        defaultSection = try container.decodeIfPresent(DefaultSection.self, forKey: .defaultSection) ?? defaultSection
        error = try container.decodeIfPresent(Error.self, forKey: .error) ?? error
    }

    public override subscript(key: String) -> LocalizableSection? {
        switch key {
        case CodingKeys.defaultSection.stringValue: return defaultSection
        case CodingKeys.error.stringValue: return error
        default: return nil
        }
    }

    public final class DefaultSection: LocalizableSection {
        public var next = ""
        public var retry = ""
        public var skip = ""
        public var no = ""
        public var edit = ""
        public var ok = ""
        public var back = ""
        public var later = ""
        public var cancel = ""
        public var previous = ""
        public var save = ""
        public var settings = ""
        public var yes = ""

        enum CodingKeys: String, CodingKey {
            case next
            case retry
            case skip
            case no
            case edit
            case ok
            case back
            case later
            case cancel
            case previous
            case save
            case settings
            case yes
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            next = try container.decodeIfPresent(String.self, forKey: .next) ?? "__next"
            retry = try container.decodeIfPresent(String.self, forKey: .retry) ?? "__retry"
            skip = try container.decodeIfPresent(String.self, forKey: .skip) ?? "__skip"
            no = try container.decodeIfPresent(String.self, forKey: .no) ?? "__no"
            edit = try container.decodeIfPresent(String.self, forKey: .edit) ?? "__edit"
            ok = try container.decodeIfPresent(String.self, forKey: .ok) ?? "__ok"
            back = try container.decodeIfPresent(String.self, forKey: .back) ?? "__back"
            later = try container.decodeIfPresent(String.self, forKey: .later) ?? "__later"
            cancel = try container.decodeIfPresent(String.self, forKey: .cancel) ?? "__cancel"
            previous = try container.decodeIfPresent(String.self, forKey: .previous) ?? "__previous"
            save = try container.decodeIfPresent(String.self, forKey: .save) ?? "__save"
            settings = try container.decodeIfPresent(String.self, forKey: .settings) ?? "__settings"
            yes = try container.decodeIfPresent(String.self, forKey: .yes) ?? "__yes"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.next.stringValue: return next
            case CodingKeys.retry.stringValue: return retry
            case CodingKeys.skip.stringValue: return skip
            case CodingKeys.no.stringValue: return no
            case CodingKeys.edit.stringValue: return edit
            case CodingKeys.ok.stringValue: return ok
            case CodingKeys.back.stringValue: return back
            case CodingKeys.later.stringValue: return later
            case CodingKeys.cancel.stringValue: return cancel
            case CodingKeys.previous.stringValue: return previous
            case CodingKeys.save.stringValue: return save
            case CodingKeys.settings.stringValue: return settings
            case CodingKeys.yes.stringValue: return yes
            default: return nil
            }
        }
    }

    public final class Error: LocalizableSection {
        public var connectionError = ""
        public var errorTitle = ""
        public var unknownError = ""
        public var authenticationError = ""

        enum CodingKeys: String, CodingKey {
            case connectionError
            case errorTitle
            case unknownError
            case authenticationError
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            connectionError = try container.decodeIfPresent(String.self, forKey: .connectionError) ?? "__connectionError"
            errorTitle = try container.decodeIfPresent(String.self, forKey: .errorTitle) ?? "__errorTitle"
            unknownError = try container.decodeIfPresent(String.self, forKey: .unknownError) ?? "__unknownError"
            authenticationError = try container.decodeIfPresent(String.self, forKey: .authenticationError) ?? "__authenticationError"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.connectionError.stringValue: return connectionError
            case CodingKeys.errorTitle.stringValue: return errorTitle
            case CodingKeys.unknownError.stringValue: return unknownError
            case CodingKeys.authenticationError.stringValue: return authenticationError
            default: return nil
            }
        }
    }
}

