// ----------------------------------------------------------------------
// File generated by NStack Translations Generator v5.0.
//
// Copyright (c) 2019 Nodes ApS
//
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of this software and associated documentation files (the
// "Software"), to deal in the Software without restriction, including
// without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to
// permit persons to whom the Software is furnished to do so, subject to
// the following conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// ----------------------------------------------------------------------

import Foundation
import NStackSDK

#if canImport(NLocalizationManager)
import NLocalizationManager
#endif

#if canImport(LocalizationManager)
import LocalizationManager
#endif

public var skl: SKLocalizations {
    return SKLocalizations()
}

public var skt: SKLocalizations { skl }

public final class SKLocalizations: LocalizableModel {
    public var defaultSection = DefaultSection()
    public var error = Error()

    enum CodingKeys: String, CodingKey {
        case defaultSection = "default"
        case error
    }

    public override init() { super.init() }

    public required init(from decoder: Decoder) throws {
        super.init()
        let container = try decoder.container(keyedBy: CodingKeys.self)
        defaultSection = try container.decodeIfPresent(DefaultSection.self, forKey: .defaultSection) ?? defaultSection
        error = try container.decodeIfPresent(Error.self, forKey: .error) ?? error
    }

    public override subscript(key: String) -> LocalizableSection? {
        switch key {
        case CodingKeys.defaultSection.stringValue: return defaultSection
        case CodingKeys.error.stringValue: return error
        default: return nil
        }
    }

    public final class DefaultSection: LocalizableSection {
        public var ok = ""
        public var back = ""
        public var settings = ""
        public var cancel = ""
        public var later = ""
        public var no = ""
        public var edit = ""
        public var retry = ""
        public var previous = ""
        public var next = ""
        public var yes = ""
        public var save = ""
        public var skip = ""

        enum CodingKeys: String, CodingKey {
            case ok
            case back
            case settings
            case cancel
            case later
            case no
            case edit
            case retry
            case previous
            case next
            case yes
            case save
            case skip
        }

        public override init() {
            super.init()
            ok = "\(classNameLowerCased()).ok"
            back = "\(classNameLowerCased()).back"
            settings = "\(classNameLowerCased()).settings"
            cancel = "\(classNameLowerCased()).cancel"
            later = "\(classNameLowerCased()).later"
            no = "\(classNameLowerCased()).no"
            edit = "\(classNameLowerCased()).edit"
            retry = "\(classNameLowerCased()).retry"
            previous = "\(classNameLowerCased()).previous"
            next = "\(classNameLowerCased()).next"
            yes = "\(classNameLowerCased()).yes"
            save = "\(classNameLowerCased()).save"
            skip = "\(classNameLowerCased()).skip"
        }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            ok = try container.decodeIfPresent(String.self, forKey: .ok) ?? "__ok"
            back = try container.decodeIfPresent(String.self, forKey: .back) ?? "__back"
            settings = try container.decodeIfPresent(String.self, forKey: .settings) ?? "__settings"
            cancel = try container.decodeIfPresent(String.self, forKey: .cancel) ?? "__cancel"
            later = try container.decodeIfPresent(String.self, forKey: .later) ?? "__later"
            no = try container.decodeIfPresent(String.self, forKey: .no) ?? "__no"
            edit = try container.decodeIfPresent(String.self, forKey: .edit) ?? "__edit"
            retry = try container.decodeIfPresent(String.self, forKey: .retry) ?? "__retry"
            previous = try container.decodeIfPresent(String.self, forKey: .previous) ?? "__previous"
            next = try container.decodeIfPresent(String.self, forKey: .next) ?? "__next"
            yes = try container.decodeIfPresent(String.self, forKey: .yes) ?? "__yes"
            save = try container.decodeIfPresent(String.self, forKey: .save) ?? "__save"
            skip = try container.decodeIfPresent(String.self, forKey: .skip) ?? "__skip"
        }

        public override subscript(key: String) -> String? {
            return ""
        }
    }

    public final class Error: LocalizableSection {
        public var unknownError = ""
        public var connectionError = ""
        public var authenticationError = ""
        public var errorTitle = ""

        enum CodingKeys: String, CodingKey {
            case unknownError
            case connectionError
            case authenticationError
            case errorTitle
        }

        public override init() {
            super.init()
            unknownError = "\(classNameLowerCased()).unknownError"
            connectionError = "\(classNameLowerCased()).connectionError"
            authenticationError = "\(classNameLowerCased()).authenticationError"
            errorTitle = "\(classNameLowerCased()).errorTitle"
        }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            unknownError = try container.decodeIfPresent(String.self, forKey: .unknownError) ?? "__unknownError"
            connectionError = try container.decodeIfPresent(String.self, forKey: .connectionError) ?? "__connectionError"
            authenticationError = try container.decodeIfPresent(String.self, forKey: .authenticationError) ?? "__authenticationError"
            errorTitle = try container.decodeIfPresent(String.self, forKey: .errorTitle) ?? "__errorTitle"
        }

        public override subscript(key: String) -> String? {
            return ""
        }
    }
}

